spring:
  application:
    name: api
  messages:
    basename: messages, errors
    encoding: utf-8

storage:
  profile-name: re-memory
  region: kr-standard
  bucket-name: re-memory-dev
  end-point: https://kr.object.ncloudstorage.com
  thumbnails[0]: /thumbnails/1.jpg

